/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nienluancs;

import java.awt.Color;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
/**
 *
 * @author Trinh Thanh Chanh
 */
public class MainForm extends javax.swing.JFrame {
    private JLabel logo;
    private JPanel board1;
    private QuanHauForm quanHau;
    private QuanMaForm quanMa;
    public MainForm() {
        initComponents();
        this.board1 = new JPanel();
        this.logo = new JLabel();
        //this.board1.setLocation(new Point(x, y));
        this.board1.setSize(100, 150);
        this.logo.setSize(100,110);
        this.board1.add(logo);
        //this.board1.setBackground(new Color(255, 255, 255));
        this.logo.setIcon(new ImageIcon(this.getClass().getResource("../Pic/logo.png")));
        this.board1.setVisible(true);
        lg.add(this.board1);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Pic/chess1.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQH = new javax.swing.JButton();
        btnQuanMa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lg = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGioithieu = new javax.swing.JMenu();
        menuTacgia = new javax.swing.JMenu();
        menuLienhe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANG CHỦ");

        btnQH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnQH.setText("8 Quân Hậu");
        btnQH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQHMouseClicked(evt);
            }
        });

        btnQuanMa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnQuanMa.setText("Quân Mã Đi Tuần");
        btnQuanMa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanMaMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bài Toán");

        javax.swing.GroupLayout lgLayout = new javax.swing.GroupLayout(lg);
        lg.setLayout(lgLayout);
        lgLayout.setHorizontalGroup(
            lgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        lgLayout.setVerticalGroup(
            lgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        menuGioithieu.setText("Giới thiệu");
        menuGioithieu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuGioithieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuGioithieuMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuGioithieu);

        menuTacgia.setText("Tác giả");
        menuTacgia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuTacgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTacgiaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuTacgia);

        menuLienhe.setText("Liên hệ");
        menuLienhe.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuLienhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLienheMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLienhe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnQH, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(btnQuanMa)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQH, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanMa, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanMaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanMaMouseClicked
        // TODO add your handling code here:
        this.quanMa = new QuanMaForm();
        this.quanMa.setMain(this);
        this.setVisible(false);
        this.quanMa.setVisible(true);
    }//GEN-LAST:event_btnQuanMaMouseClicked

    private void btnQHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQHMouseClicked
        this.quanHau = new QuanHauForm();
        this.quanHau.setMain(this);
        this.setVisible(false);
        this.quanHau.setVisible(true);

    }//GEN-LAST:event_btnQHMouseClicked

    private void menuGioithieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuGioithieuMouseClicked
        // TODO add your handling code here:
        String gioithieu = new String();
        gioithieu = "Với mục đích tạo ra chương trình nhằm giải quyết và mô tả bài tán 8 quna6 Hậu và quân mã đi tuần trong bàn cờ Vua một cách trực quan nhất.\n"
                +"Giúp cho người xem có thể hiểu được cách hoạt động của thuật toán để giải quyết hai bài toán trên.\n"+
                "Đồng thời đây cũng là sản phẩm hoàn thành đề tài thuộc học phần CT239 - Niên luận cơ sở ngành Kỹ thuật phần mềm.";
       JDialog dialog = new JDialog();
       dialog.setAlwaysOnTop(true);
       JOptionPane.showMessageDialog(dialog, gioithieu);
    }//GEN-LAST:event_menuGioithieuMouseClicked

    private void menuTacgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTacgiaMouseClicked
        // TODO add your handling code here:
        String tacgia = new String();
        tacgia = "TRỊNH THÀNH CHÁNH"
                    +"\n"+
                "CHI ĐOÀN: Kỹ THUẬT PHẦN MỀM 01 K44 (DI1896A1)\n"+
                "MSSV: B1805743\n"+
                "Quê quán: Vĩnh Long\n";
       JDialog dialog = new JDialog();
       dialog.setAlwaysOnTop(true);
       JOptionPane.showMessageDialog(dialog, tacgia);
    }//GEN-LAST:event_menuTacgiaMouseClicked

    private void menuLienheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLienheMouseClicked
        // TODO add your handling code here:
        String lienhe = new String();
        lienhe = "Mọi liên hệ hoặc thắc mắc:\n"+
                "TRỊNH THÀNH CHÁNH\n"+
                "SĐT: (+84) 939405518\n"+
                "EMAIL: chanhB1805743@student.ctu.edu.vn";
       JDialog dialog = new JDialog();
       dialog.setAlwaysOnTop(true);
       JOptionPane.showMessageDialog(dialog, lienhe);
    }//GEN-LAST:event_menuLienheMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQH;
    private javax.swing.JButton btnQuanMa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel lg;
    private javax.swing.JMenu menuGioithieu;
    private javax.swing.JMenu menuLienhe;
    private javax.swing.JMenu menuTacgia;
    // End of variables declaration//GEN-END:variables
}
